<script type="text/javascript">
    require([
        'jquery',
        'prototype'
    ], function ($) {
        $operation_mode = $('carriers_yellowcube_operation_mode');
        if ($operation_mode.length > 0) {
            Event.observe($operation_mode, 'change', function (event) {
                if (this.value == '<?php echo Swisspost\YellowCube\Model\Shipping\Carrier\Source\Operation::MODE_PRODUCTION ?>') {
                    $('carriers_yellowcube_certificate_path').addClassName('required-entry');
                } else {
                    $('carriers_yellowcube_certificate_path').removeClassName('required-entry');
                }
            });
        }
    });
</script>
